name: Build kPad for Windows (Nuitka)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka customtkinter

      # Nuitka build
      - name: Build with Nuitka
        run: |
          python -m nuitka --standalone --onefile --windowed --name=kPad-Windows_xxw86_64 main.py

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kPad-Windows_x86_64
          path: main.dist/kPad-Windows_x86_64.exe